### ISSUE TITLE
Week 1: Tip Calc

### ISSUE THREAD

**Issue by msniff16** [mamuso/codepath-tip-calculator#2]
# Tip Calculator for Codepath - Please review

This application is an exercise to complete the application to Codepath's iOS for Designers bootcamp. 
 @codepathreview
Time: I spent around 1 hour on the exercise
## What does the app can do?
- [x] Required: The user can calculate the tip, using different percentages 

Walkthrough of all the app stories:

![Video](https://cloud.githubusercontent.com/assets/1372815/9892433/9069b180-5bc3-11e5-8a27-4c44fc43d583.gif)
ps.gif)
## What did I miss?
- [x] Should have spent more time messing with optional add ons.

The GIF was created with [LiceCap](http://www.cockos.com/licecap/).

**Comment by mamuso** [comment]
Are you posting in the right place?
