### ISSUE TITLE
Pre-work Tip Calculator for Codepath

### ISSUE THREAD

**Issue by brainus** [mamuso/codepath-tip-calculator#3]
@codepathreview

This application is an exercise to complete the application to Codepath's iOS for Designers bootcamp. There is not a huge investement on design nor a lot of complex code behind it, the exercise triest to touch

Time: I spent 3 hours on the exercise
What does the app can do?

```
Required: The user can calculate the tip, using diferent percentages
```

Walkthrough of all the app stories:

Video Walkthrough

![bills demo](https://cloud.githubusercontent.com/assets/13801600/10092108/e2c40800-62f7-11e5-95d2-86e10fe59cc6.gif)

What did I miss?

The GIF was created with LiceCap.

**Comment by mamuso** [comment]
Hi @brainus, you should push the project to your own repository and open the issue there
